# Name (appears in top header bar)
title: Resources
# Description (appears immediately below title)
description: Tools for research

remote_theme: pmarsceill/just-the-docs
# theme: jekyll-theme-architect

