# Name (appears in top header bar)
title: Peter Charlton's Resources
# Description (appears immediately below title)
description: Tools for research
# tagline
tagline: Biomedical signal processing tools
# author
author: Peter H Charlton
# google site verification
google-site-verification: google49454546bc54e329.html

remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  rel_url: false
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3

aux_links:
  "Accompanying code":
    - "https://github.com/peterhcharlton/resources"

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Peter Charlton."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
