# Name (appears in top header bar)
title: Resources
description: Tools for biomedical signal processing research


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-architect

